apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-app
    spec:
      containers:
        - name: {{ .Values.name }}-app-container
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "1000m"
            requests:
              memory: "64Mi"
              cpu: "500m"
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: my-secret
    