name: gateway
image: 1qwaka/gateway:v1.5
containerPort: 8080
clusterPort: 80

env:
  PORT: '8080'
  RESERVATION_URL: http://reservation-svc:80
  PAYMENT_URL: http://payment-svc:80
  LOYALTY_URL: http://loyalty-svc:80
  REDIS_HOST: ''
  # сейчас не используется, чисто чтобы не падало приложение
  REDIS_PORT: '1111'
  IDP_URL: http://idp-svc:80/auth
  IDP_ISSUER: http://localhost:80
  REDIRECT_URI: http://my-app.local/callback
  KAFKA_BROKER: kafka-svc:29092
  STATISTICS_URL: http://statistics-svc:80


secretRefs: 
- 'oidc-data'