name: loyalty
image: 1qwaka/loyalty:v1.4
containerPort: 8080
clusterPort: 80

env:
  PORT: '8080'
  DB_NAME: loyalties
  DB_PORT: '5432'
  DB_HOST: postgres-postgresql
  IDP_URL: http://idp-svc:80/auth
  IDP_ISSUER: http://localhost:80

secretRefs: 
- 'oidc-data'